// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include "Handler.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>


#include "colordescriptor.h"


using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ImageHandle;

class HandlerHandler : virtual public HandlerIf {
 public:
  HandlerHandler() {
    // Your initialization goes here
  }

  void Feature(std::vector<double> & _return, const std::string& image) {
    // Your implementation goes here
    //std::cout<<image.length()<<","<<image.size()<<std::endl;
    if (image.size() == 0) {
      std::cout<<"input image size is 0byte, please input a correct image"<<std::endl;
      return;
    }
    ColorDescriptor cd = ColorDescriptor();
    cd.describe(image, _return);
  }

  void DeepLearning(Result& _return, const std::string& image) {
    // Your implementation goes here
    std::cout<<"DeepLearning"<<std::endl;
  }
  void ObjectDetectionDL(Result& _return, const std::string& image) {
    // Your implementation goes here
    std::cout<<"ObjectDetectionDL"<<std::endl;
  }
};


int main(int argc, char **argv) {
  int port = 9091;
  shared_ptr<HandlerHandler> handler(new HandlerHandler());
  shared_ptr<TProcessor> processor(new HandlerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

