// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Handler.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ImageHandle;

class HandlerHandler : virtual public HandlerIf {
 public:
  HandlerHandler() {
    // Your initialization goes here
  }

  void Feature(std::vector<double> & _return, const std::string& image) {
    // Your implementation goes here
    printf("Feature\n");
  }

  void DeepLearning(Result& _return, const std::string& image) {
    // Your implementation goes here
    printf("DeepLearning\n");
  }

  void ObjectDetectionDL(Result& _return, const std::string& image) {
    // Your implementation goes here
    printf("ObjectDetectionDL\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HandlerHandler> handler(new HandlerHandler());
  shared_ptr<TProcessor> processor(new HandlerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

