/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ImageHandle_CONSTANTS_H
#define ImageHandle_CONSTANTS_H

#include "ImageHandle_types.h"

namespace ImageHandle {

class ImageHandleConstants {
 public:
  ImageHandleConstants();

};

extern const ImageHandleConstants g_ImageHandle_constants;

} // namespace

#endif
