/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ImageHandle_constants.h"

namespace ImageHandle {

const ImageHandleConstants g_ImageHandle_constants;

ImageHandleConstants::ImageHandleConstants() {
}

} // namespace

